###Health Check
GET http://localhost:5000/health HTTP/1.1


### get tasks
GET http://localhost:5000/v1/tasks HTTP/1.1

### get tasks by id
GET http://localhost:5000/v1/tasks/1 HTTP/1.1

### get projects
GET http://localhost:5000/v1/projects HTTP/1.1

### get projects by id
GET http://localhost:5000/v1/projects/1 HTTP/1.1

### get project's tasks
GET http://localhost:5000/v1/projects/1/tasks HTTP/1.1